#
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2022 hugcabbage <fengsongtianxia@gmail.com>
#
# This is free software, licensed under the MIT License.
#
#<https://github.com/hugcabbage/shared-lede>
#
# 源码采用lean lede或者lienol openwrt master分支
#
name: Auto MT7621
on:
  workflow_dispatch:
    inputs:
      build:
        description: 'To compile, type true'
        required: true
        default: 'true'
      model:
        description: 'Select Model'
        required: true
        default: 'xiaomi-4a-gigabit' 
        type: choice
        options:
        - mi-router-4a-gigabit
        - mi-router-3g-v2
        - mi-router-ac2100
        - redmi-router-ac2100
        - mi-router-cr6606
        - mi-router-cr6608
        - mi-router-cr6609
        - mi-router-3g
        - mi-router-4
        - mi-router-3-pro
        - phicomm_k2p
        - totolink_x5000r
      version_description:
        description: 'Enter version description'     
        required: true
        default: '升级内容：内核升级，更新应用版本'
      cpu_overclock:
        description: 'Overclocked to 1100Mhz (5.10 kernel only)'
        required: false
        default: 'false'
        type: boolean
      kernel_5_15:
        description: 'Use 5.15 kernel'
        required: false
        default: 'false'
        type: boolean
      release:
        description: 'Upload to release'
        required: false
        default: 'true'
        type: boolean
      artifact:
        description: 'Upload to artifact'
        required: false
        default: 'false'
        type: boolean
env:
  TARGET_SE: preset-models/target_select.py
  RELEASE_CO: preset-models/release_content.yml
  CLONE_SH: preset-models/temp.clone.sh
  MODIFY_SH: preset-models/temp.modify.sh
  CONFIG_PA: preset-models/temp.config
jobs:
  build_openwrt:
    name: Firmware Compilation
    runs-on: ubuntu-latest
    if: github.event.inputs.build == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialization environment
        run: |
          #sudo rm -rf /usr/share/dotnet /etc/mysql /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
          #sudo -E apt-get -y purge ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 zip unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
      - name: Model Selection
        id: select
        run: |
          NUMBER=$(python3 $TARGET_SE ${{ github.event.inputs.model }})
          echo "你选择了：${{ github.event.inputs.model }}"
          RELEASE_TITLE=$(yq ".model_${NUMBER}.title" $RELEASE_CO)
          RELEASE_BODY=$(yq ".model_${NUMBER}.body[]" $RELEASE_CO); RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"; RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"
          echo "::set-output name=RELEASE_TITLE::$RELEASE_TITLE"
          echo "::set-output name=RELEASE_BODY::$RELEASE_BODY"
      - name: Download Source & Plug-ins
        run: |
          chmod +x $CLONE_SH
          $CLONE_SH
      - name: Update Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Change Setting
        run: |
          [ ${{ github.event.inputs.cpu_overclock }} == true ] && sed -i '/322-mt7621-fix-cpu-clk-add-clkdev.patch/ s/#//' $MODIFY_SH
          [ ${{ github.event.inputs.kernel_5_15 }} == true ] && sed -i '/KERNEL_PATCHVER:=5.15/ s/#//' $MODIFY_SH
          chmod +x $MODIFY_SH
          $MODIFY_SH
      - name: Generate .config file
        run: |
          mv -f $CONFIG_PA ./.config
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make Download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
      - name: Compile
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
      - name: Organize Directory
        run: |
          mkdir -p ./collected_firmware/packages
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./collected_firmware
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./collected_firmware/packages
          cd collected_firmware
          zip -r ./allfiles.zip ./*
          cd packages
          zip -r ../packages.zip ./*
      - name: Get Current Date
        run: |
          CURRENT_TIME=$(TZ=Asia/Shanghai date +'%y.%-m.%-d.%H%M%S'); CURRENT_TIME=${CURRENT_TIME:1}
          echo "TAG_NAME=${CURRENT_TIME}" >> $GITHUB_ENV
          echo "RELEASE_PRE=${CURRENT_TIME%.*}" >> $GITHUB_ENV
      - name: Upload To Release
        id: upload-release
        if: github.event.inputs.release == 'true' && env.RELEASE_FIRMWARE_VALUE != ''
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_FIRMWARE }}
          file: collected_firmware/*
          tag: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_PRE }} ${{ steps.select.outputs.RELEASE_TITLE }}
          overwrite: true
          prerelease: false
          body: |
            ${{ steps.select.outputs.RELEASE_BODY }}
            ${{ github.event.inputs.version_description }}
          file_glob: true
        env:
          RELEASE_FIRMWARE_VALUE: ${{ secrets.RELEASE_FIRMWARE }}
      - name: Upload To Artifact
        if: github.event.inputs.artifact == 'true' || steps.upload-release.conclusion == 'skipped'
        uses: actions/upload-artifact@v3
        with:
          name: collected_firmware
          path: |
            collected_firmware/
            !collected_firmware/*.zip
